namespace: demo-reader

app:
  name: reader
  port: 8084
  managementPort: 8081
  image: reader:0.1.0
  imagePullPolicy: Never
  replicaCount: 1

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 768Mi

database:
  username: postgres
  password: postgres123
  database: postgres

dependencies:
  postgres:
    host: postgresql.postgres.svc.cluster.local
    port: 5432
  back:
    host: back.demo-back.svc.cluster.local
    port: 8082

ingress:
  enabled: true
  hostname: reader.local
