apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  namespace: {{ .Values.namespace }}
data:
  application.yaml: |
    server:
      port: {{ .Values.app.port }}
    spring:
      datasource:
        url: jdbc:postgresql://{{ .Values.dependencies.postgres.host }}:{{ .Values.dependencies.postgres.port }}/{{ .Values.database.database }}
        driverClassName: org.postgresql.Driver
      jpa:
        hibernate:
          ddl-auto: validate
    management:
      server:
        port: {{ .Values.app.managementPort }}
        address: 0.0.0.0
      endpoints:
        web:
          base-path: /
          exposure:
            include: health,info,metrics
