{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: {{ .Values.namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: reader-egress
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: reader
  policyTypes:
  - Egress
  egress:
  # allow only psql
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: postgres
      podSelector:
        matchLabels:
          app: postgresql
    ports:
    - port: {{ .Values.dependencies.postgres.port }}
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.dependencies.back.namespace }}
      podSelector:
        matchLabels:
          app: back
    ports: 
    - port: {{ .Values.dependencies.back.managementPort}}
# dns for FQDN 
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: reader-ingress
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: reader
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
    ports:
    - port: {{ .Values.app.port }}
{{- end }}