apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ required "database.username is required" .Values.database.username | b64enc }}
  password: {{ required "database.password is required" .Values.database.password | b64enc }}
