apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.postgres.auth.username | b64enc }}
  password: {{ .Values.postgres.auth.password | b64enc }}