apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: {{ .Values.namespace }}
  labels:
    app: postgresql
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.postgres.port }}
    targetPort: postgres
    protocol: TCP
    name: postgres
  selector:
    app: postgresql
