namespace: demo-front

app:
  name: front
  port: 8080
  managementPort: 8081
  image: front:0.1.0
  imagePullPolicy: Never
  imagePullSecrets: []
  replicaCount: 1

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 768Mi

dependencies:
  kafka:
    host: kafka.kafka.svc.cluster.local
    port: 9092

networkPolicy:
  enabled: true

ingress:
  enabled: true
  className: nginx
  hostname: front.local
  tls:
    enabled: true
    tlsSecret: front-tls
    cert: ""
    key: ""
