namespace: postgres

postgres:
  image: postgres:16
  port: 5432
  database: postgres

  auth:
    username: ""
    password: ""

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

  persistence:
    size: 5Gi

networkPolicy:
  enabled: false

dependencies:
  back:
    namespace: demo-back
  reader:
    namespace: demo-reader
