apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: {{ .Values.namespace }}
data:
  KAFKA_NODE_ID: "1"
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_LISTENERS: "PLAINTEXT://:{{ .Values.kafka.port }},CONTROLLER://:9093"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.kafka.port }}"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
  KAFKA_LOG_DIRS: "/tmp/kafka-logs"
  CLUSTER_ID: "5L6g3nShT-eMCtK--X86sw"