apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{ .Values.namespace }}
  labels:
    app: kafka
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.kafka.port }}
    targetPort: kafka
    protocol: TCP
    name: kafka
  selector:
    app: kafka
