apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: {{ .Values.namespace }}
  labels:
    app: kafka
spec:
  serviceName: kafka
  replicas: {{ .Values.kafka.brokers }}
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: kafka
        image: {{ .Values.kafka.image }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        ports:
        - containerPort: {{ .Values.kafka.port }}
          name: kafka
        - containerPort: 9093
          name: controller
        envFrom:
        - configMapRef:
            name: kafka-config
        volumeMounts:
        - name: kafka-data
          mountPath: /var/kafka-logs
        - name: tmp
          mountPath: /tmp
        resources:
          requests:
            cpu: {{ .Values.kafka.resources.requests.cpu }}
            memory: {{ .Values.kafka.resources.requests.memory }}
          limits:
            cpu: {{ .Values.kafka.resources.limits.cpu }}
            memory: {{ .Values.kafka.resources.limits.memory }}
        startupProbe:
          tcpSocket:
            port: {{ .Values.kafka.port }}
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: {{ .Values.kafka.port }}
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: {{ .Values.kafka.port }}
          periodSeconds: 5
          failureThreshold: 3
      volumes:
      - name: tmp
        emptyDir: {}

  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.kafka.persistence.size }}