# helm/front/templates/tls-secret.yaml
{{- if .Values.ingress.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.tlsSecret }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
type: kubernetes.io/tls
stringData:
  tls.crt: {{ required "ingress.tls.cert is required" .Values.ingress.tls.cert | quote }}
  tls.key: {{ required "ingress.tls.key is required" .Values.ingress.tls.key | quote }}
{{- end}}  